### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by nayrnet** [davidnewhall/unifi-poller#82] opened 2019-07-12 21:00 UTC
Trying to poll my uniFi controller and the docker container crashes:

```2019/07/12 20:43:48 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
2019/07/12 20:43:48 [INFO] UniFi Poller v1.5.0-334 Starting Up! PID: 1
2019/07/12 20:43:48 [INFO] Authenticated to UniFi Controller at https://192.168.4.2:8443 version 5.10.25 as user influxdb

2019/07/12 20:43:48 [INFO] Found 3 site(s) on controller: default (Denco), i32jdkuu (Backup), c41eonlp (GalileoNET)

2019/07/12 20:43:48 [INFO] Polling UniFi Controller Sites: [all]

2019/07/12 20:43:48 [INFO] Logging Measurements to InfluxDB at http://192.168.69.10:8086 as user unifi
2019/07/12 20:43:48 [INFO] Everything checks out! Poller started, interval: 30s
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x66c39c]

goroutine 1 [running]:
github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi.UAP.PointsAt(0xc00034e2a0, 0x18, 0x1, 0xc000350408, 0x4, 0x0, 0x0, 0x0, 0xc000350410, 0x9, ...)
/go/src/github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi/uap_influx.go:22 +0x18c
github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi.UAP.Points(0xc00034e2a0, 0x18, 0x1, 0xc000350408, 0x4, 0x0, 0x0, 0x0, 0xc000350410, 0x9, ...)
/go/src/github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi/uap_influx.go:12 +0x86
github.com/davidnewhall/unifi-poller/unifipoller.(*Metrics).processPoints(0xc00001a300, 0x85e7e0, 0xc000300000, 0xc000300000, 0x0)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:191 +0x3a
github.com/davidnewhall/unifi-poller/unifipoller.(*Metrics).ProcessPoints(0xc00001a300, 0xc000460d78, 0x7, 0x40c7ae0000000000)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:175 +0x52d
github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).ReportMetrics(0xc00009c300, 0xc00001a300, 0x0, 0x0)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:129 +0x43
github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).CollectAndReport(0xc00009c300, 0xc000213e00, 0x6fc23ac01)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:73 +0x95
github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).PollController(0xc00009c300, 0x0, 0x0)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:52 +0x14f
github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).Run(0xc00009c300, 0x0, 0x0)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/start.go:101 +0x24d
github.com/davidnewhall/unifi-poller/unifipoller.Start(0x40584f, 0xc00007a058)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/start.go:33 +0x11e
main.main()
/go/src/github.com/davidnewhall/unifi-poller/main.go:11 +0x26
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x66c39c]

goroutine 1 [running]:
github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi.UAP.PointsAt(0xc00034e2a0, 0x18, 0x1, 0xc000350408, 0x4, 0x0, 0x0, 0x0, 0xc000350410, 0x9, ...)
/go/src/github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi/uap_influx.go:22 +0x18c
github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi.UAP.Points(0xc00034e2a0, 0x18, 0x1, 0xc000350408, 0x4, 0x0, 0x0, 0x0, 0xc000350410, 0x9, ...)
/go/src/github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi/uap_influx.go:12 +0x86
github.com/davidnewhall/unifi-poller/unifipoller.(*Metrics).processPoints(0xc00001a300, 0x85e7e0, 0xc000300000, 0xc000300000, 0x0)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:191 +0x3a
github.com/davidnewhall/unifi-poller/unifipoller.(*Metrics).ProcessPoints(0xc00001a300, 0xc000460d78, 0x7, 0x40c7ae0000000000)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:175 +0x52d
github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).ReportMetrics(0xc00009c300, 0xc00001a300, 0x0, 0x0)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:129 +0x43
github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).CollectAndReport(0xc00009c300, 0xc000213e00, 0x6fc23ac01)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:73 +0x95
github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).PollController(0xc00009c300, 0x0, 0x0)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:52 +0x14f
github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).Run(0xc00009c300, 0x0, 0x0)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/start.go:101 +0x24d
github.com/davidnewhall/unifi-poller/unifipoller.Start(0x40584f, 0xc00007a058)
/go/src/github.com/davidnewhall/unifi-poller/unifipoller/start.go:33 +0x11e
main.main()
/go/src/github.com/davidnewhall/unifi-poller/main.go:11 +0x26````

**Comment by davidnewhall** [comment] 2019-07-12 21:58
uh oh. I'm looking into this. Can you try v1.4.2? There is a tag for it.

I'm a little stumped how it's failing on influx `points` code when it has not printed any messages about collecting data (to put into influx). hmm..

Is it running in lambda mode by chance?

**Comment by davidnewhall** [comment] 2019-07-12 23:04
I think I found the problem I just don't understand why I can't reproduce it.

**Comment by nayrnet** [comment] 2019-07-13 00:57
its due to deactivated devices, I tried specifying a site and it crashed.. moved the deactivated device to another site and now it works.

**Comment by davidnewhall** [comment] 2019-07-13 01:20
Got it, sounds like the `stat` data is missing in those cases. The next release should contain a fix for this. I'll get a new docker `latest` push out sometime today or tomorrow. Will update here when I do, and I'd really appreciate it if you could try to reproduce the issue after installing it.
Thanks!

**Comment by davidnewhall** [comment] 2019-07-13 11:07
The referenced pull request has been merged to master which triggers a Docker Hub build to re-create the `latest` tag. That takes 15-30 minutes. Please try the new tag once it's published; I'm very confident this change solves the problem you've reported.

**Comment by tfs** [comment] 2019-07-15 06:17
Hmm. Should that be fixed in current stable? I still get that error on 1.5.0-333, running in docker.
Log looks exactly the same - I can post it if its of any use. (yes, I have one switch in my site which is currently not online.)

**Comment by davidnewhall** [comment] 2019-07-15 06:18
Not in `stable` yet. Stable is only based on new releases. I'm still updating a few things before I cut a new release. This should be fixed in `latest`.

**Comment by davidnewhall** [comment] 2019-07-15 06:20
I also just put some new build stuff (Docker specifically into `:minor2`) that will finish building in the next ~10 minutes. Would appreciate if you could test it in a few.

**Comment by tfs** [comment] 2019-07-15 06:31
Tested latest (1.5.0-349) - still crashing.

**Comment by davidnewhall** [comment] 2019-07-15 06:33
Please put it in debug mode and attach the logs. I'm a bit stumped.

**Comment by tfs** [comment] 2019-07-15 07:00
Starting unifi-poller ...
Starting unifi-poller ... done
Attaching to unifi-poller
unifi-poller    | 2019/07/15 06:58:37 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
unifi-poller    | 2019/07/15 06:58:37.404520 start.go:88: [DEBUG] Debug Logging Enabled
unifi-poller    | 2019/07/15 06:58:37.404559 start.go:90: [INFO] UniFi Poller v1.5.0-349 Starting Up! PID: 1
unifi-poller    | 2019/07/15 06:58:38.185362 start.go:130: [INFO] Authenticated to UniFi Controller at https://192.168.1.33:8443 version 5.11.31 as user influx
unifi-poller    | 2019/07/15 06:58:38.196049 unifi.go:132: [DEBUG] Found 2 site(s): cg738hkc,default
unifi-poller    | 2019/07/15 06:58:38.196084 unifi.go:28: [INFO] Found 2 site(s) on controller: cg738hkc (XXX), default (XX)
unifi-poller    | 2019/07/15 06:58:38.196120 start.go:134: [INFO] Polling UniFi Controller Sites: [all]
unifi-poller    | 2019/07/15 06:58:38.196142 start.go:117: [INFO] Logging Measurements to InfluxDB at http://192.168.1.34:8086 as user unifi
unifi-poller    | 2019/07/15 06:58:38.196160 unifi.go:49: [INFO] Everything checks out! Poller started, interval: 30s
unifi-poller    | 2019/07/15 06:59:08.207478 unifi.go:132: [DEBUG] Found 2 site(s): cg738hkc,default
unifi-poller    | 2019/07/15 06:59:08.207532 unifi.go:80: [DEBUG] Polling Controller, retreiving UniFi Clients, site cg738hkc (XXX)
unifi-poller    | 2019/07/15 06:59:08.216307 unifi.go:80: [DEBUG] Polling Controller, retreiving UniFi Clients, site default (XX)
unifi-poller    | 2019/07/15 06:59:08.247750 devices.go:16: [DEBUG] Unmarshalling Device Type: ugw, site XXX (cg738hkc)
unifi-poller    | 2019/07/15 06:59:08.251119 devices.go:16: [DEBUG] Unmarshalling Device Type: uap, site XXX (cg738hkc)
unifi-poller    | 2019/07/15 06:59:08.257791 devices.go:16: [DEBUG] Unmarshalling Device Type: usw, site XXX (cg738hkc)
unifi-poller    | 2019/07/15 06:59:08.264947 devices.go:16: [DEBUG] Unmarshalling Device Type: uap, site XXX (cg738hkc)
unifi-poller    | 2019/07/15 06:59:08.269221 devices.go:16: [DEBUG] Unmarshalling Device Type: usw, site XXX (cg738hkc)
unifi-poller    | 2019/07/15 06:59:08.270637 devices.go:16: [DEBUG] Unmarshalling Device Type: usw, site XXX (cg738hkc)
unifi-poller    | 2019/07/15 06:59:08.274876 devices.go:16: [DEBUG] Unmarshalling Device Type: uap, site XXX (cg738hkc)
unifi-poller    | panic: runtime error: invalid memory address or nil pointer dereference
unifi-poller    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x67f141]
unifi-poller    |
unifi-poller    | goroutine 1 [running]:
unifi-poller    | github.com/davidnewhall/unifi-poller/vendor/code.golift.io/unifi.(*USW).PointsAt(0xc00043c800, 0xbf4326ef0bb2706d, 0x72b70816f, 0xab22c0, 0xc00015c400, 0xb, 0x10, 0x0, 0x0)
unifi-poller    |   /go/src/github.com/davidnewhall/unifi-poller/vendor/code.golift.io/unifi/usw_influx.go:22 +0x171
unifi-poller    | github.com/davidnewhall/unifi-poller/unifipoller.(*Metrics).processPoints(0xc0000e0500, 0x8592a0, 0xc00043c800, 0x0, 0x0)
unifi-poller    |   /go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:191 +0x5d
unifi-poller    | github.com/davidnewhall/unifi-poller/unifipoller.(*Metrics).ProcessPoints(0xc0000e0500, 0xc000373440, 0x7, 0x45c40a8500000000)
unifi-poller    |   /go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:181 +0x786
unifi-poller    | github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).ReportMetrics(0xc0000fd110, 0xc0000e0500, 0x0, 0x0)
unifi-poller    |   /go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:129 +0x43
unifi-poller    | github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).CollectAndReport(0xc0000fd110, 0xc0001ede00, 0x6fc23ac01)
unifi-poller    |   /go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:73 +0x95
unifi-poller    | github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).PollController(0xc0000fd110, 0x0, 0x0)
unifi-poller    |   /go/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:52 +0x177
unifi-poller    | github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).Run(0xc0000fd110, 0x0, 0x0)
unifi-poller    |   /go/src/github.com/davidnewhall/unifi-poller/unifipoller/start.go:103 +0x284
unifi-poller    | github.com/davidnewhall/unifi-poller/unifipoller.Start(0x40584f, 0xc00006a058)
unifi-poller    |   /go/src/github.com/davidnewhall/unifi-poller/unifipoller/start.go:34 +0x11e
unifi-poller    | main.main()
unifi-poller    |   /go/src/github.com/davidnewhall/unifi-poller/main.go:11 +0x26

**Comment by davidnewhall** [comment] 2019-07-15 07:09
Another docker build will be done in ~15 minutes. Should be fixed. The tag will be `:minor2` (until I merge #85 - then it goes to `:latest`).

**Comment by tfs** [comment] 2019-07-15 07:23
v1.5.0-351? This is still crashing.

**Comment by davidnewhall** [comment] 2019-07-15 07:23
it's not done yet. 351 was the last build on that tag., it's just rebuild my branch/PR when I push to it. The builds take ~15 minutes, sometimes longer. :(

**Comment by tfs** [comment] 2019-07-15 07:34
Last Build on docker hub is from 8:29 CEST - one hour ago.

**Comment by davidnewhall** [comment] 2019-07-15 07:35
it's done. Try this one.
```shell
$ docker pull golift/unifi-poller:minor2
minor2: Pulling from golift/unifi-poller
83b8ecf32e3b: Pull complete
68075129a5c5: Pull complete
Digest: sha256:86ffa446744adea7423e00242d69ee2e0598af862ef5e7eecd1777d80e1498f5
Status: Downloaded newer image for golift/unifi-poller:minor2

$ docker run golift/unifi-poller:minor2 -v
unifi-poller v1.5.0-353
```

**Comment by tfs** [comment] 2019-07-15 07:37
This one works. UniFi Poller v1.5.0-353, [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 30, Wireless APs: 3, Gateways: 1, Switches: 3, Points: 97, Fields: 4059

Thanks!

**Comment by davidnewhall** [comment] 2019-07-15 07:38
Sweet! Thank you for reporting this! I totally missed fixing usg and usw when I fixed uap.. They're good now. The version you're using now should be stable, and the changes it has will be in the next release. Really appreciate your help!

**Closed** 2019-07-15 07:56 UTC

**Comment by davidnewhall** [comment] 2019-07-17 09:32
The current release (1.5.1) solves this issue. Please upgrade!
