### ISSUE TITLE
No data in Grafana

### ISSUE THREAD

**Issue by rottison** [davidnewhall/unifi-poller#77] opened 2019-07-10 19:39 UTC
I am running the newest dashboards from the grafana website as of 7/9 I have them installed in grafana on my unraid server.
I have unifi-poller_1.4.2-133_armhf.deb installed on Pi3 B+ with unifi controller V5.10.25 that is sent to influxDB installed on my UnRaid server along with grafana I made a new data base in Influx named unifi. I use the data source in grafana to point to it and to the url of the unraid box. all internal ip's I am getting no data to the grafana graphs and I am using the unifi database that I made in the source box under edit in grafana

EDIT (davidnewhall):
From [original post](https://github.com/davidnewhall/unifi-poller/issues/47#issuecomment-510131274): 
```
Jul 10 12:09:43 controller unifi-poller[3102]: 2019/07/10 12:09:43 [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 18, Wireless APs: 2, Gateways: 1, Switches: 1, Points: 51, Fields: 2186
```

**Comment by davidnewhall** [comment] 2019-07-10 19:58
Try creating a new graph, something simple like UAP CPU usage. Does the data show up at all? The fields in grafana should try to auto populate with data from influx. The names of the tables, etc. Try to make a simple graph like the one in this screenshot:
![uap-cpu-min](https://user-images.githubusercontent.com/2402929/61000474-5b6b2c80-a312-11e9-9038-5686d1251ae8.png)

I feel like the problem is in the data source configuration. Grafana seems unable to pull data from InfluxDB for some reason. For an example, this is what my data source looks like:
![unifi-data-source-min](https://user-images.githubusercontent.com/2402929/61000489-63c36780-a312-11e9-84af-89a7ef8498bd.png)

**Comment by rottison** [comment] 2019-07-10 20:25
That seems to be getting data but it is the same data source I am pointing the others at 

![image](https://user-images.githubusercontent.com/6868854/61001727-2a98f080-a32e-11e9-9cfb-f692f6abb4f2.png)

![image](https://user-images.githubusercontent.com/6868854/61002326-5072c500-a32f-11e9-98ad-3cc5c927064b.png)

**Comment by rottison** [comment] 2019-07-10 20:31
I downloaded the poller script on 7/7 if that makes a difference I thought it was 7/9 but it might be older than what is currently there

**Comment by davidnewhall** [comment] 2019-07-10 20:39
That looks good. You even have data! So we're mostly there. 

That screenshot I took for UAP CPU (that you just replicated) was taken directly from the UAP Insights Dashboard. I edited the CPU graph and removed the `WHERE` clauses then took a screenshot.  This should be working. 

Try some very basic things? Restart influx. Restart grafana-server.  Edit one of the existing graphs (like CPU on UAP dash) and see if you can get it to work without the WHERE clauses, then added the WHERE clauses back. 

Check the Variables: Edit the dashboard, click variables. Click on one of the variables. Examples values should be displayed. Do you see those? Your screenshot is low quality and I cannot make out the name of your WAP. Does it have a name? Make sure all devices have unique names. Your poller output shows two UAPs, but only one shows in your graph screenshot. Is that expected? That may indicate a variable/name problem.

**Comment by rottison** [comment] 2019-07-10 20:54
sorry about that
![image](https://user-images.githubusercontent.com/6868854/61004141-4ce13d00-a333-11e9-96e5-2e68a412433a.png)
I have 2 UAP's just 1 is unplugged for now moving it to a different room

**Comment by davidnewhall** [comment] 2019-07-10 21:02
Add group by `tag(name)`. 
Let me know if you can figure anything out with my previous troubleshooting steps.

**Comment by rottison** [comment] 2019-07-10 21:03
in the FROM field if I remove every thing after the Where statement I get data

**Comment by rottison** [comment] 2019-07-10 21:06
![image](https://user-images.githubusercontent.com/6868854/61004939-1c020780-a335-11e9-8959-4087c09cd044.png)

**Comment by rottison** [comment] 2019-07-10 21:17
seems to work as long as there is nothing after the Where in the From line

![image](https://user-images.githubusercontent.com/6868854/61005677-a39c4600-a336-11e9-820d-c92ddc659659.png)

**Comment by rottison** [comment] 2019-07-10 21:19
![image](https://user-images.githubusercontent.com/6868854/61005816-e0683d00-a336-11e9-80fe-f644d107a9ac.png)

**Comment by rottison** [comment] 2019-07-10 21:27
looks like i can do Where name =USG to fix no data showing or at least on a couple I have fixed so far

**Comment by rottison** [comment] 2019-07-10 21:33
under USG insights what do you have for Lan throughput I can not get that one to work

**Comment by davidnewhall** [comment] 2019-07-11 01:14
Sorry been a busy day!
![usg lan-min](https://user-images.githubusercontent.com/2402929/61014935-9420fb00-a33e-11e9-9cb2-df47647ea4bb.png)

**Comment by rottison** [comment] 2019-07-11 01:37
nothing is showing up after adding the variables back in, has there been any changes in the scripts or some thing from your set to my version from 3 days ago? I also wanted to ask when manually installing the .deb file from the releases section does that in stall Go also?

**Comment by davidnewhall** [comment] 2019-07-11 01:48
Nothing has changed in the past few days. I uploaded some dashboards to grafana on like the 7th, but that was it. The old dashboards still worked, they just had a few pieces that weren't great. What you're experiencing seems to be a grafana issue with variables. What version of grafana are you running? All of this was built and tested on 6.2. Your screenshots look like 6.2 so i dont think that's it. 

Have you looked at the variables in the dashboard settings? Do they show example values?

The binary packages on the releases page have no dependencies. That means they do not install anything besides unifi-poller (already compiled). Go is not installed.

**Comment by rottison** [comment] 2019-07-11 01:56
I am using grafana 6.2.5.
do I need to install golang on the pi for this to work correctly? I used apt-get install and it installed golang but there is a newer version out  
 when i click on the different boxes under edit the variables are there just need to click on them. To populate the boxes.

**Comment by davidnewhall** [comment] 2019-07-11 01:59
You do not need go lang or any compiling tools installed to use the poller. Just install the package and it works. You're at the point of "poller is working, data is in influx, grafana is having troubles displaying it."

Do you have discord? Can we jump into a chat maybe and share your screen? I may be able to help figure this out. I'm a bit stumped over here.

**Comment by rottison** [comment] 2019-07-11 02:15
ok got it reinstalled but not very good at using it

**Comment by rottison** [comment] 2019-07-11 02:18
discord I mean

**Comment by davidnewhall** [comment] 2019-07-11 02:19
Jump in here. https://discord.gg/GgeGADs

**Comment by Waffull** [comment] 2019-07-11 02:33
FYI, after updating to device firmware 4.0.49, I had to restart both
unifi-poller and grafana to get it to start displaying data again.  Doubt
it has anything to do with the problem you're working through, but just
figured I'd share that piece of info.

**Comment by davidnewhall** [comment] 2019-07-11 02:38
We actually jumped into a discord and found his issue. The variables in the dashbaord had the wrong data source. This could be a problem with how I exported them, I'm not sure. @rottison has a pretty good path forward to fix this at least. @Waffull - please open yet another issue and paste your logs from the poller after the firmware update. Curious if it start printing zeros.

**Comment by Waffull** [comment] 2019-07-11 02:55
My brain has already shut down for the night..  Remind me where the log
files are located.

**Comment by davidnewhall** [comment] 2019-07-11 02:58
on linux? logs are going to be in syslog. Usually /var/log/syslog or /var/log/messages.
Try this
`sudo grep unifi-poller /var/log/syslog /var/log/messages | tail -n 100`

**Comment by Waffull** [comment] 2019-07-11 03:03
Can that be piped out to a file?
Also, I did the upgrade lastnight, so I'm going to have to pull from
further back in the logs.

**Comment by davidnewhall** [comment] 2019-07-11 03:09
sure. pipe to file. attach that somewhere or gist it.
```shell
sudo grep unifi-poller /var/log/syslog /var/log/messages | tail -n 100 | tee my_file_poller_dataz.txt
```

**Comment by davidnewhall** [comment] 2019-07-11 05:39
I'm going to close this one out. If you need more help @rottison hit me up.

**Closed by davidnewhall** 2019-07-11 05:39 UTC

**Comment by davidnewhall** [comment] 2019-08-25 21:00
The problem turned out to be: **The variables in the dashbaord had the wrong data source.**
